spring:
  main:
    web-application-type: servlet
  application:
    name: talki_spring

  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
      file-size-threshold: 10MB
server:
  port: 8080
  address: 0.0.0.0
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1
fastapi:
  url: http://localhost:8000