spring:
  main:
    web-application-type: servlet
  application:
    name: talki_spring

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD:}

  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
      file-size-threshold: 10MB
jwt:
  base64Secret: dGhpc2lzMzJiYXl0ZXNlY3JldGtleWZvcnRlc3Rpbmc=
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create

server:
  port: 8080
  address: 0.0.0.0
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1

fastapi:
  url: http://localhost:8000

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: talki-recordings

