name: Deploy to Dev (Java 21)

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 소스 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # JDK 21 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

#      # application-dev.yml 생성 (GitHub Secrets → 파일)
#      - name: Make application-dev.yml
#        run: |
#          mkdir -p ./src/main/resources
#          echo "$PROPERTIES_DEV" > ./src/main/resources/application-dev.yml
#        env:
#          PROPERTIES_DEV: ${{ secrets.PROPERTIES_DEV }}

      # Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # Docker 이미지 메타데이터 설정
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: juheenoh/talki_spring
          tags: |
            type=ref,event=branch
            type=sha

      # Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # DockerHub 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker 이미지 빌드 & Push
      - name: Docker build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.dev
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}

      # EC2 원격 디렉토리 생성
      - name: Create remote directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USER_DEV }}
          key: ${{ secrets.KEY_DEV }}
          script: |
            mkdir -p ~/dev

      # 소스 코드 EC2로 복사
      - name: Copy source to EC2
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          remote_path: ~/dev
          remote_host: ${{ secrets.HOST_DEV }}
          remote_user: ${{ secrets.USER_DEV }}
          remote_key: ${{ secrets.KEY_DEV }}

      # EC2에서 배포 실행
      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USER_DEV }}
          key: ${{ secrets.KEY_DEV }}
          script: |
            cd ~/dev
            export REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            export MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            sh ./config/scripts/deploy.sh
            
